/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventariosRouteImport } from './routes/inventarios'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PlaneacionRouteImport } from './routes/planeacion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventariosRoute = InventariosRouteImport.update({
  id: '/inventarios',
  path: '/inventarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaneacionRoute = PlaneacionRouteImport.update({
  id: '/planeacion',
  path: '/planeacion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventarios': typeof InventariosRoute
  '/pedidos': typeof PedidosRoute
  '/planeacion': typeof PlaneacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventarios': typeof InventariosRoute
  '/pedidos': typeof PedidosRoute
  '/planeacion': typeof PlaneacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventarios': typeof InventariosRoute
  '/pedidos': typeof PedidosRoute
  '/planeacion': typeof PlaneacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inventarios' | '/pedidos' | '/planeacion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventarios' | '/pedidos' | '/planeacion'
  id: '__root__' | '/' | '/inventarios' | '/pedidos' | '/planeacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventariosRoute: typeof InventariosRoute
  PedidosRoute: typeof PedidosRoute
  PlaneacionRoute: typeof PlaneacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventarios': {
      id: '/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof InventariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planeacion': {
      id: '/planeacion'
      path: '/planeacion'
      fullPath: '/planeacion'
      preLoaderRoute: typeof PlaneacionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventariosRoute: InventariosRoute,
  PedidosRoute: PedidosRoute,
  PlaneacionRoute: PlaneacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
